"""empty message

Revision ID: 1098004da4b0
Revises: b344d8a1fb6b
Create Date: 2016-10-14 19:58:53.542151

"""

# revision identifiers, used by Alembic.
revision = '1098004da4b0'
down_revision = 'b344d8a1fb6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    ### end Alembic commands ###
