"""empty message

Revision ID: 23bfc4315490
Revises: d1809b069daf
Create Date: 2016-10-14 22:26:42.913403

"""

# revision identifiers, used by Alembic.
revision = '23bfc4315490'
down_revision = 'd1809b069daf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_column('resources', 'location_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('location_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'resources', 'locations', ['location_id'], ['id'])
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('longitude', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
