"""empty message

Revision ID: 3fbf9a06647c
Revises: 23bfc4315490
Create Date: 2016-10-14 22:29:57.657032

"""

# revision identifiers, used by Alembic.
revision = '3fbf9a06647c'
down_revision = '23bfc4315490'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'longitude')
    op.drop_column('resources', 'latitude')
    ### end Alembic commands ###
